[dependencies]
base = "0.11.1"
http-types = "1.0.1"
map = "9.0.1"
certified-assets = "0.3.0"
ic = "1.0.1"
itertools = "0.2.1"
vector = "0.3.1"
sha2-shared = "https://github.com/NatLabs/sha2#main@b3578003e29c4a297f01efc70eb295243d0e44fa"
encoding = "https://github.com/aviate-labs/encoding.mo#v0.4.1@2711d18727e954b11afc0d37945608512b5fbce2"
http-parser = "0.3.1"

[dev-dependencies]
test = "2.0.0"
bench = "1.0.0"
fuzz = "0.2.1"

[toolchain]
wasmtime = "15.0.0"
moc = "0.11.1"
